pool:
  name: SelfPool


jobs:
    - job: BuildArchive
      steps:       
        - task: CmdLine@2
          inputs:
           script: |
            ls
            echo hello
            mkdir '$(Build.BinariesDirectory)/workingDir'
            mv Rap*.zip '$(Build.BinariesDirectory)/workingDir'
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
