pool:
  name: SelfPool


jobs:
    - job: BuildArchive
      steps:       
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'dev'
            publishLocation: 'Container'