pool:
  name: SelfPool


jobs:
    - job: BuildArchive
      steps:       
        - task: CmdLine@2
          inputs:
           script: |
            ls
            echo hello
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'dev'
            publishLocation: 'Container'