pool:
  name: SelfPool


jobs:
    - job: BuildArchive
      steps:       
        - task: CmdLine@2
          inputs:
           script: |
            ls
            echo hello
            mkdir '$(Build.SourcesDirectory)/workingDir'
            
            ls $(Build.BinariesDirectory)/workingDir

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)/workingDir/'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        - publish: '$(Build.ArtifactStagingDirectory)/'
          artifact: dev
          displayName: Publish Dev artifact
