pool:
  name: SelfPool

stages:
- stage: Dev

  jobs:
   - job: Upload
     displayName: 'Upload contents'
     steps:
     - task: DownloadPipelineArtifact@2
       inputs:
        buildType: 'specific'
        project: 'c5dd1afd-7930-4f3d-a83c-52f2bbf29611'
        definition: '5'
        buildVersionToDownload: 'latest'
        targetPath: '$(Pipeline.Workspace)'
     - task: CmdLine@2
       inputs:
            script: |
             
             mv *.zip ./backup
             cd ./backup
             ls
            
